const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWU4vT05tM0grc05RRkpJNnpBL21DQzVhRlBCcWV3b1JQdGxhTFJEZ0QwVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNlF2MERQSFhxQysxMGJDbUhZQVkxNHI4VHBZNzhrQWVYcEU4aUZTbVFocz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIyRTNKcWlaSVMrUVF4a3FpWmM4S0NsZ2ljT2ZoTVE5cWhTSlpUK3NhLzN3PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJheU5qak1aUlQrbXJZeTRDazh0K0tKTmE3WEhQYVRvSlRoUGRJV1F1dXhRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1JUCtrM0VRNUNSTnFVZWlGV0RqU1VJK0lVaWZ2dlNoUW01VlgyajV4M3M9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImpTcTBpVGlsTWRmc0FxOVhzNzlJSm1mOVZOcmJRdEpBN1JtY1Q5K0lHaDA9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYU83eUFBOWZEWmFDaFpjcENsM2JVemNDVkJnVTEzdGlSaEJ0V0MrMFJsbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSmx0WnBUUTc3RUR4RXVPV0R4WUY3M3NpNjVNOXRYN1JFWmJiYmxtM0doYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ink2bmlUWjh2cmhWSHRUMU9EcW1VMmltUDFwQ3lsWWd6RHhUY29GTEFCSS9hTURxRmdsY3A1bXFONWhGWDRWMXB2bHM2NkE2UllGV0xwb0dyelhVUmd3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODQsImFkdlNlY3JldEtleSI6InIwaG5DMklpdmJwR1hCNFN2QkFnS1piS3dwOTgyV25NMWswendrakd5ZW89IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzNDUzOTQwMTg2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjNBMTlCNUVBMjUzQzcyN0QxRDIyQjBDN0NBRTk1RDVFIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDI5Njk1MTl9LHsia2V5Ijp7InJlbW90ZUppZCI6IjkyMzQ1Mzk0MDE4NkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBODMwNDkyMURDNzgxMTA5OENEODc4MDM0MjY5MkRGNCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQyOTY5NTIwfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJoZ2JKelpSb1RaLWdKLTFIR1FycEVBIiwicGhvbmVJZCI6ImY1NTdmODA2LTAyYzMtNDI3Zi04Zjc0LWYzYmI3YWYyZTEwNyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIybERlY2FhcmJOb25aZEVBVjYyTnhsUzVOd0k9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiODVpY25GSHR3Vi9qMzJMbGh0R2ZHckdDeHhrPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkNFTEJUMlNGIiwibWUiOnsiaWQiOiI5MjM0NTM5NDAxODY6MThAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiSGkifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0lMN3BBVVFrYldPdndZWUF5QUFLQUE9IiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjlBTnErQlNXMW85R2YzVGc0YjgzYWdwaU41UStycHQwVnplYkRweEhmeGM9IiwiYWNjb3VudFNpZ25hdHVyZSI6IndvNmdLTFNDdUM4d3NEb0EzMG9rV2h0eFh2RFpENFRZRFpMeVFjaGpWY1hBcWN2QklnbVJKTkpoNVQrVlBreS9QamczSTZzb3plUFVZa1ZEdEpPZUJRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJseWsxVkdhS0FSdUhxeEJMNXZWMEQ4U1UzQ01ZU0JKdlhxUUtvVWNHblhQVTF2LzFKK3V0azZvUEcwOUZRakE3ejJPaTljUGZzSldJRFFHaTVmekFqQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjkyMzQ1Mzk0MDE4NjoxOEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJmUURhdmdVbHRhUFJuOTA0T0cvTjJvS1lqZVVQcTZiZEZjM213NmNSMzhYIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzQyOTY5NTAzLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU5GWiJ9",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
